'use strict';
(() => {
 const $ = id => document.getElementById(id);
 const all = window.ISOC_DIRECTORY?.offers || [];
 let saved = new Set();
 try {const stored=JSON.parse(localStorage.getItem('swansea-isoc-saved-v2') || '[]');if(Array.isArray(stored)) saved=new Set(stored.filter(x=>typeof x==='string'));}catch(e){}
 let kind='all', opener=null, toastTimer;
 const escape = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const url = value => {try {const u=new URL(value,location.href);return ['https:','http:'].includes(u.protocol)?u.href:'#';}catch(e){return '#';}};
 const icon = name => {const paths={pin:'<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/>',arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',external:'<path d="M7 17 17 7M7 7h10v10"/>',save:'<path d="M6 4h12v17l-6-4-6 4z"/>',card:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18m-14 5h4"/>'};return `<svg viewBox="0 0 24 24" aria-hidden="true">${paths[name]||paths.arrow}</svg>`;};
 const directions = o => 'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(o.name+', '+o.address);
 const date = d => new Date(d+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
 const today = new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const visible = o => o.status!=='hidden' && ['active','pending'].includes(o.status) && (!o.expires || o.expires>=today);
 const pending = o => o.status!=='active' || (o.food && o.halalChecked!==true);
 const logo = o => `<div class="logo-box"><img src="${escape(o.logo)}" alt="${escape(o.name)} logo" width="70" height="70" loading="lazy"><span class="logo-fallback" hidden>${escape(o.name)}</span></div>`;
 function images(root=document){root.querySelectorAll('.logo-box img').forEach(img=>{const fallback=()=>{img.hidden=true;img.nextElementSibling.hidden=false;};img.addEventListener('error',fallback,{once:true});if(img.complete&&!img.naturalWidth) fallback();});}
 function message(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,2400);}
 function toggleSave(id){saved.has(id)?saved.delete(id):saved.add(id);let persisted=true;try{localStorage.setItem('swansea-isoc-saved-v2',JSON.stringify([...saved]));}catch(e){persisted=false;}render();message(persisted?(saved.has(id)?'Place saved':'Place removed'):'Saved for this visit');}
 function offerCard(o){const p=pending(o);return `<article class="offer" id="place-${escape(o.id)}"><div class="offer-top"><span class="tag ${p?'pending':''}">${p?'Confirmation pending':escape(o.kind==='card'?'ISOC card benefit':'Student offer')}</span><button class="save" data-save="${escape(o.id)}" aria-label="${saved.has(o.id)?'Unsave':'Save'} ${escape(o.name)}" aria-pressed="${saved.has(o.id)}">${icon('save')}</button></div><div class="offer-main">${logo(o)}<div class="business"><h3>${escape(o.name)}</h3><p>${escape(o.area)}</p></div><div class="offer-amount">${escape(o.rate)}<small>${p?'proposed':'off'}</small></div></div><p class="offer-line">${escape(o.summary || o.benefit)}</p><p class="claim-line">${icon('card')}<span>${escape(p?'Not yet available to claim':o.claim)}</span></p><div class="offer-footer"><button data-offer="${escape(o.id)}">Offer details ${icon('arrow')}</button>${o.address?`<a href="${escape(directions(o))}" target="_blank" rel="noopener noreferrer" aria-label="Directions to ${escape(o.name)}">${icon('pin')} Directions</a>`:''}</div></article>`;}
 function render(){
   const q=$('search').value.trim().toLowerCase();const category=$('category').value;const area=$('area').value;
   const offers=all.filter(o=>visible(o)&&(kind==='all'||(kind==='saved'?saved.has(o.id):o.kind===kind))&&(!category||o.category===category)&&(!area||o.area===area)&&(!q||[o.name,o.category,o.area,o.summary,o.rate,o.claim].join(' ').toLowerCase().includes(q)));
   $('saved-count').textContent=all.filter(o=>visible(o)&&saved.has(o.id)).length;$('clear').hidden=!q;
   document.querySelectorAll('[data-kind]').forEach(b=>{b.classList.toggle('active',b.dataset.kind===kind);b.setAttribute('aria-pressed',String(b.dataset.kind===kind));});
   $('results').textContent=offers.length+' '+(offers.length===1?'place':'places')+(kind==='saved'?' saved':' in the directory');
   let html='';
   for(const k of ['card','student']){const group=offers.filter(o=>o.kind===k);if(!group.length)continue;const anyActive=group.some(o=>!pending(o));const title=k==='card'?'ISOC card benefits':'Student offers';const description=k==='card'?(anyActive?'Present your ISOC discount card.':'Cardholder offers are being finalised.'):'Claim with the student ID or account shown.';html+=`<section class="group"><div class="group-heading"><h2>${title}<span>${group.length.toString().padStart(2,'0')}</span></h2><p>${description}</p></div><div class="offer-grid">${group.map(offerCard).join('')}</div></section>`;}
   $('offers').innerHTML=html;$('empty').hidden=offers.length>0;if(kind==='saved'&&!offers.length){$('empty').querySelector('h2').textContent='Your shortlist starts here.';$('empty').querySelector('p').textContent='Use the bookmark on an offer to save it.';}else{$('empty').querySelector('h2').textContent='No matches this time.';$('empty').querySelector('p').textContent='Try another area, category or search.';}images($('offers'));
 }
 function showOffer(id,updateHash=true){
   const o=all.find(o=>o.id===id&&visible(o));if(!o)return;opener=document.activeElement;const p=pending(o);
   $('dialog-type').textContent=o.kind==='card'?'ISOC CARD BENEFIT':'GENERAL STUDENT OFFER';
   $('dialog-content').innerHTML=`<div class="detail-head">${logo(o)}<div><h2 id="dialog-title">${escape(o.name)}</h2><p>${escape(o.category)} · ${escape(o.area)}</p></div></div><div class="detail-value"><strong>${escape(o.rate)}</strong><span>${escape(o.benefit)}${p?'<br>Proposed · confirmation pending':''}</span></div>${p?`<p class="pending-note">This offer is not yet active. ${escape(o.food?'Final terms and branch halal information are awaiting confirmation.':'Final terms are awaiting confirmation.')}</p>`:`<h3 class="detail-label">How to claim</h3><ol class="steps">${o.steps.map(s=>'<li>'+escape(s)+'</li>').join('')}</ol>`}${o.terms.length?`<h3 class="detail-label">Offer conditions</h3><ul class="detail-terms">${o.terms.map(t=>'<li>'+escape(t)+'</li>').join('')}</ul>`:''}<h3 class="detail-label">Find it in Swansea</h3><p class="detail-location">${escape(o.address)}</p><div class="detail-actions">${o.address?`<a class="button" href="${escape(directions(o))}" target="_blank" rel="noopener noreferrer">${icon('pin')} Get directions</a>`:''}${o.website?`<a class="button secondary" href="${escape(url(o.website))}" target="_blank" rel="noopener noreferrer">${p?'Business website':'Visit offer page'} ${icon('external')}</a>`:''}</div><div class="detail-source">${o.locationUrl?`<a href="${escape(url(o.locationUrl))}" target="_blank" rel="noopener noreferrer">Location & opening hours ↗</a>`:''}${o.sourceUrl?`<a href="${escape(url(o.sourceUrl))}" target="_blank" rel="noopener noreferrer">${escape(o.source)} ↗</a>`:''}${o.checked?`<span>Offer checked ${date(o.checked)}</span>`:''}${o.expires?`<span>Ends ${date(o.expires)}</span>`:''}</div><button class="share-offer" data-share="${escape(o.id)}">Share this offer ↗</button><div id="copy-fallback"></div>`;
   images($('dialog-content'));if(!$('offer-dialog').open)$('offer-dialog').showModal();$('close-dialog').focus();if(updateHash)history.replaceState(null,'','#offer='+encodeURIComponent(o.id));
 }
 async function share(id){const link=new URL(location.href);link.hash='offer='+encodeURIComponent(id);try{await navigator.clipboard.writeText(link.href);message('Offer link copied');}catch(e){const input=document.createElement('input');input.className='copy-input';input.readOnly=true;input.value=link.href;input.setAttribute('aria-label','Link to this offer');$('copy-fallback').replaceChildren(input);input.focus();input.select();message('Select and copy the offer link');}}
 function reset(){kind='all';$('search').value='';$('category').value='';$('area').value='';render();}
 for(const [id,key] of [['category','category'],['area','area']]){[...new Set(all.filter(visible).map(o=>o[key]))].sort().forEach(v=>{const opt=document.createElement('option');opt.value=v;opt.textContent=v;$(id).append(opt);});$(id).addEventListener('change',render);}
 document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;if(el.dataset.kind){kind=el.dataset.kind;render();}if(el.dataset.save)toggleSave(el.dataset.save);if(el.dataset.offer)showOffer(el.dataset.offer);if(el.dataset.share)share(el.dataset.share);if(el.hasAttribute('data-help')){$('help-dialog').showModal();$('close-help').focus();}});
 $('search').addEventListener('input',render);$('clear').addEventListener('click',()=>{$('search').value='';render();$('search').focus();});$('reset').addEventListener('click',reset);
 $('close-dialog').addEventListener('click',()=>$('offer-dialog').close());$('close-help').addEventListener('click',()=>$('help-dialog').close());
 for(const id of ['offer-dialog','help-dialog']){$(id).addEventListener('click',e=>{if(e.target===$(id)){const r=$(id).getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$(id).close();}});}
 $('offer-dialog').addEventListener('close',()=>{if(location.hash.startsWith('#offer='))history.replaceState(null,'',location.pathname+location.search+'#directory');const target=opener?.dataset?.offer?document.querySelector('[data-offer="'+CSS.escape(opener.dataset.offer)+'"]'):opener;if(target?.isConnected)target.focus();});
 $('back-top').addEventListener('click',e=>{e.preventDefault();window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});
 window.addEventListener('hashchange',()=>{if(location.hash.startsWith('#offer='))showOffer(decodeURIComponent(location.hash.slice(7)),false);});
 render();if(location.hash.startsWith('#offer='))showOffer(decodeURIComponent(location.hash.slice(7)),false);
})();
