/* Edit offer details here. status: active, pending, or hidden.
   Food offers must have halalChecked:true AND status:'active' to become claimable.
   All files in this repository are public. Keep private contacts and negotiations elsewhere. */
window.ISOC_DIRECTORY = {edition:'2026–27', offers:[
 {id:'wokway',name:'Wokway',kind:'card',category:'Food & drink',status:'pending',rate:'15%',benefit:'ISOC card discount',summary:'Noodles, rice boxes and Chinese takeaway.',area:'The Kingsway',address:'68 The Kingsway, Swansea, SA1 5HW',logo:'logos/wokway.jpg',claim:'ISOC discount card',food:true,halalChecked:false,halalNote:'Branch halal information and final offer terms await confirmation.',steps:['Present your ISOC discount card before ordering.','Confirm eligible items with the Swansea branch.'],terms:['Cardholder offer awaiting final confirmation.'],source:'ISOC offer list',sourceUrl:'https://maroneaosman-rgb.github.io/ISOC-Discount/',website:'https://www.wok-way.co.uk/swansea/',locationUrl:'https://www.wok-way.co.uk/swansea/contact-us.html',checked:'',expires:'',phone:'01792951260'},
 {id:'aces',name:'Ace’s Desserts',kind:'card',category:'Food & drink',status:'pending',rate:'15%',benefit:'ISOC card discount',summary:'Waffles, milkcakes and desserts on High Street.',area:'High Street',address:'35 High Street, Swansea, SA1 1LG',logo:'logos/aces.jpg',claim:'ISOC discount card',food:true,halalChecked:false,halalNote:'Branch halal information and final offer terms await confirmation.',steps:['Show your ISOC discount card before ordering.','Check which items are included before paying.'],terms:['High Street branch only is listed for review.','Cardholder offer awaiting final confirmation.'],source:'ISOC offer list',sourceUrl:'https://maroneaosman-rgb.github.io/ISOC-Discount/',website:'https://acesdessertsonline.co.uk/',locationUrl:'https://acesdessertsonline.co.uk/',checked:'',expires:'',phone:''},
 {id:'boots',name:'Boots',kind:'student',category:'Essentials',status:'active',rate:'10%',benefit:'off eligible purchases',summary:'Student savings on everyday essentials.',area:'The Quadrant',address:'17 The Quadrant, Swansea, SA1 3AD',logo:'logos/boots.svg',claim:'Advantage Card + valid student ID',food:false,steps:['Join Boots Advantage Card or use your existing card.','Visit a staffed till with your Advantage Card and valid student ID to activate the discount.','Use your Advantage Card in store or online. Renew student verification each academic year.'],terms:['Exclusions apply, including prescriptions and selected products and services.','Student activation is valid until 31 August; check current Boots terms.'],source:'Boots student discount',sourceUrl:'https://www.boots.com/student-discount',website:'https://www.boots.com/student-discount',locationUrl:'https://www.boots.com/stores/280-swansea-the-quadrant-sa1-3ad',checked:'2026-09-20',expires:'',phone:'01792643461'},
 {id:'superdrug',name:'Superdrug',kind:'student',category:'Essentials',status:'active',rate:'10%',benefit:'off eligible purchases',summary:'Everyday essentials. Maximum £5 saving per order.',area:'The Quadrant',address:'35–36 The Quadrant, Swansea, SA1 3QW',logo:'logos/superdrug.png',claim:'Beautycard + student verification',food:false,steps:['Register for a Superdrug Health & Beautycard.','In store, show your Beautycard and valid student ID.','For online purchases, use the current Superdrug offer through Student Beans.'],terms:['Maximum £5 discount on a £50 spend per transaction.','Product and service exclusions apply. Gift-card and points payments are excluded as set out in the provider terms.'],source:'Student Beans · Superdrug',sourceUrl:'https://www.studentbeans.com/student-discount/uk/superdrug',website:'https://www.studentbeans.com/student-discount/uk/superdrug',locationUrl:'https://www.superdrug.com/store/swansea',checked:'2026-09-20',expires:'',phone:'01792466668'},
 {id:'schuh',name:'schuh',kind:'student',category:'Shopping',status:'active',rate:'10%',benefit:'student discount',summary:'Footwear in store and online.',area:'The Quadrant',address:'Unit 31, St Mary’s Arcade, The Quadrant, Swansea, SA1 3QW',logo:'logos/schuh.png',claim:'Student ID or verified online code',food:false,steps:['Show valid student ID at the till.','Online, obtain a code through Student Beans, UNiDAYS or TOTUM.','Apply your code before completing payment.'],terms:['Product exclusions apply; consult the current exclusion list.','One discount per transaction. Cannot be combined with other offers.'],source:'schuh student discount',sourceUrl:'https://www.schuh.co.uk/help/student-discount/',website:'https://www.schuh.co.uk/help/student-discount/',locationUrl:'https://www.schuh.co.uk/stores/swansea/',checked:'2026-09-20',expires:'',phone:'01792825749'},
 {id:'specsavers',name:'Specsavers',kind:'student',category:'Essentials',status:'active',rate:'25%',benefit:'off glasses from £70',summary:'Glasses from £70, with standard single-vision lenses.',area:'The Kingsway',address:'394–395 The Kingsway, Swansea, SA1 5LQ',logo:'logos/specsavers.png',claim:'Valid student photo ID',food:false,steps:['Choose an eligible pair of glasses priced from £70.','Present valid student photo ID or a TOTUM card when purchasing in store.','Ask staff to apply the student offer to your eligible pair.'],terms:['In store only; one complete pair with standard single-vision prescription lenses.','Cannot be combined with other offers. Excludes reglazes, safety eyewear, contact lens products and non-prescription sunglasses.'],source:'Specsavers student offer',sourceUrl:'https://www.specsavers.co.uk/offers/student-glasses-discount',website:'https://www.specsavers.co.uk/offers/student-glasses-discount',locationUrl:'https://www.specsavers.co.uk/stores/swansea',checked:'2026-09-20',expires:'',phone:'01792474426'},
 {id:'kaspas',name:'Kaspa’s Desserts',kind:'student',category:'Food & drink',status:'hidden',rate:'10%',benefit:'student discount',summary:'',area:'Swansea',address:'',logo:'logos/kaspas.png',claim:'Student ID',food:true,halalChecked:false,halalNote:'Current Swansea discount, location and halal details are not verified.',steps:[],terms:[],source:'ISOC offer list',sourceUrl:'https://maroneaosman-rgb.github.io/ISOC-Discount/',website:'',locationUrl:'',checked:'',expires:'',phone:''}
]};
