/* SWANSEA ISOC — OFFER DIRECTORY
   Edit this file, not the page layout. You can also use the included offline offer editor.
   status: "draft" = hidden; "review" = shown in preview only; "published" = live.
   previewMode: true shows review entries with warnings; false shows published entries only.
   Drafts in this file are NOT private: a public GitHub repository makes the source public.
   Never put personal contacts, private negotiations, passwords or membership data here.
*/
window.ISOC_DATA = {
  "site": {
    "name": "Swansea ISOC",
    "year": "2026 / 27",
    "previewMode": true,
    "lastUpdated": "2026-09-16",
    "contactEmail": "",
    "instagramUrl": ""
  },
  "offers": [
    {
      "id": "wokway",
      "name": "Wokway",
      "kind": "exclusive",
      "category": "Food & drink",
      "status": "review",
      "discount": "15% off",
      "strapline": "A stop on The Kingsway.",
      "area": "City centre",
      "address": "68 The Kingsway, Swansea, SA1 5HW",
      "claimMethod": "ISOC discount card",
      "steps": [
        "Show your ISOC discount card before ordering.",
        "Ask staff to confirm which items the offer covers."
      ],
      "terms": [
        "15% is the rate in the committee’s existing draft.",
        "Participating branch, exclusions and validity still need a final committee check."
      ],
      "sourceLabel": "ISOC’s supplied discount list",
      "sourceUrl": "https://maroneaosman-rgb.github.io/ISOC-Discount/",
      "locationSourceUrl": "https://www.wok-way.co.uk/swansea/",
      "checkedOn": "",
      "expiresOn": "",
      "food": true,
      "halalStatus": "unconfirmed",
      "halalNote": "The Swansea ordering listing is tagged halal. This is not a halal certificate; the committee still needs to confirm the current position with this branch.",
      "halalSourceUrl": "https://www.ubereats.com/gb/store/wokway/mcM-8busUQ66ak7ppNghqg",
      "note": "Verify the branch, written offer terms and halal information before publishing."
    },
    {
      "id": "aces-desserts",
      "name": "Ace’s Desserts",
      "kind": "exclusive",
      "category": "Food & drink",
      "status": "review",
      "discount": "15% off",
      "strapline": "Something sweet on High Street.",
      "area": "City centre",
      "address": "35 High Street, Swansea, SA1 1LG",
      "claimMethod": "ISOC discount card",
      "steps": [
        "Show your ISOC discount card before ordering.",
        "Confirm the offer with staff before paying."
      ],
      "terms": [
        "15% is the rate in the committee’s existing draft.",
        "Branch participation, eligible items and end date are not yet recorded."
      ],
      "sourceLabel": "ISOC’s supplied discount list",
      "sourceUrl": "https://maroneaosman-rgb.github.io/ISOC-Discount/",
      "locationSourceUrl": "https://acesdessertsonline.co.uk/",
      "checkedOn": "",
      "expiresOn": "",
      "food": true,
      "halalStatus": "unconfirmed",
      "halalNote": "The High Street ordering listing is tagged halal. Current ingredients and halal status still need confirming directly with the venue.",
      "halalSourceUrl": "https://www.ubereats.com/gb/store/aces-desserts/JxbEBDjQVK2JE-AQJwe12Q",
      "note": "Do not assume the same agreement covers the Gorseinon branch."
    },
    {
      "id": "kaspas",
      "name": "Kaspa’s Desserts",
      "kind": "general",
      "category": "Food & drink",
      "status": "review",
      "discount": "10% off",
      "strapline": "A student offer, not an ISOC partnership.",
      "area": "City centre",
      "address": "",
      "claimMethod": "Student ID",
      "steps": [
        "Ask the Swansea branch whether the student offer is currently available.",
        "Show the student identification the branch accepts before paying."
      ],
      "terms": [
        "The 10% rate and student ID requirement come from the committee’s draft.",
        "Current Swansea terms and halal information have not been independently confirmed."
      ],
      "sourceLabel": "ISOC’s supplied discount list",
      "sourceUrl": "https://maroneaosman-rgb.github.io/ISOC-Discount/",
      "locationSourceUrl": "",
      "checkedOn": "",
      "expiresOn": "",
      "food": true,
      "halalStatus": "unconfirmed",
      "halalNote": "Branch-level halal information has not yet been confirmed. Do not publish as halal until this is checked.",
      "halalSourceUrl": "",
      "note": "The 50% Swansea promotion found on an SU page ended 30 March 2025; do not reuse it."
    },
    {
      "id": "boots",
      "name": "Boots",
      "kind": "general",
      "category": "Everyday essentials",
      "status": "published",
      "discount": "10% off",
      "strapline": "A little off your everyday essentials.",
      "area": "The Quadrant",
      "address": "17 The Quadrant, Swansea, SA1 3AD",
      "claimMethod": "Advantage Card + student ID",
      "steps": [
        "Join Boots Advantage Card, or use your existing card.",
        "Take your Advantage Card and valid student ID to a staffed till to activate the student discount.",
        "Use your Advantage Card when paying. Reactivate your student discount each academic year from 1 September."
      ],
      "terms": [
        "Available on eligible purchases, in store and online.",
        "Excludes prescriptions and selected products and services; check Boots’ full terms.",
        "The ISOC discount card is not a substitute for student verification."
      ],
      "sourceLabel": "Boots student discount",
      "sourceUrl": "https://www.boots.com/student-discount",
      "locationSourceUrl": "https://www.boots.com/stores/280-swansea-the-quadrant-sa1-3ad",
      "checkedOn": "2026-09-16",
      "expiresOn": "",
      "food": false,
      "halalStatus": "not-applicable",
      "halalNote": "",
      "halalSourceUrl": "",
      "note": "A researched general-student addition. This is not an ISOC-negotiated offer. It is a toiletries/essentials listing, not a halal certification of the whole retailer."
    },
    {
      "id": "superdrug",
      "name": "Superdrug",
      "kind": "general",
      "category": "Everyday essentials",
      "status": "published",
      "discount": "10% off",
      "strapline": "Student savings at The Quadrant.",
      "area": "The Quadrant",
      "address": "35–36 The Quadrant, Swansea, SA1 3QW",
      "claimMethod": "Student Beans + Beautycard",
      "steps": [
        "Have a Superdrug Health & Beautycard and valid student identification ready.",
        "Open the Superdrug offer on Student Beans and check the current instructions.",
        "Show the required student ID and Beautycard in store, or use the verified code online."
      ],
      "terms": [
        "Student Beans currently lists a maximum £5 saving on a £50 spend per transaction.",
        "Product, service and payment exclusions apply. Read the current provider terms.",
        "This is a general student offer, not an ISOC-exclusive discount."
      ],
      "sourceLabel": "Student Beans · Superdrug",
      "sourceUrl": "https://www.studentbeans.com/student-discount/uk/superdrug",
      "locationSourceUrl": "https://www.superdrug.com/store/swansea",
      "checkedOn": "2026-09-16",
      "expiresOn": "",
      "food": false,
      "halalStatus": "not-applicable",
      "halalNote": "",
      "halalSourceUrl": "",
      "note": "A researched general-student addition. Limit and eligibility should be rechecked regularly."
    },
    {
      "id": "velvet-green",
      "name": "Velvet Green",
      "kind": "exclusive",
      "category": "Food & drink",
      "status": "draft",
      "discount": "",
      "strapline": "",
      "area": "Swansea",
      "address": "",
      "claimMethod": "",
      "steps": [],
      "terms": [],
      "sourceLabel": "",
      "sourceUrl": "",
      "locationSourceUrl": "",
      "checkedOn": "",
      "expiresOn": "",
      "food": true,
      "halalStatus": "unconfirmed",
      "halalNote": "",
      "halalSourceUrl": "",
      "note": "Listed as Discount TBC in the supplied draft. Confirm rate, terms, Swansea location and halal details before making visible."
    },
    {
      "id": "hello-asia",
      "name": "Hello Asia",
      "kind": "exclusive",
      "category": "Food & drink",
      "status": "draft",
      "discount": "",
      "strapline": "",
      "area": "Swansea",
      "address": "",
      "claimMethod": "",
      "steps": [],
      "terms": [],
      "sourceLabel": "",
      "sourceUrl": "",
      "locationSourceUrl": "",
      "checkedOn": "",
      "expiresOn": "",
      "food": true,
      "halalStatus": "unconfirmed",
      "halalNote": "",
      "halalSourceUrl": "",
      "note": "Listed as Discount TBC in the supplied draft. Confirm rate, terms, Swansea location and halal details before making visible."
    },
    {
      "id": "madcow",
      "name": "MadCow",
      "kind": "exclusive",
      "category": "Food & drink",
      "status": "draft",
      "discount": "",
      "strapline": "",
      "area": "Swansea",
      "address": "",
      "claimMethod": "",
      "steps": [],
      "terms": [],
      "sourceLabel": "",
      "sourceUrl": "",
      "locationSourceUrl": "",
      "checkedOn": "",
      "expiresOn": "",
      "food": true,
      "halalStatus": "unconfirmed",
      "halalNote": "",
      "halalSourceUrl": "",
      "note": "Listed as Discount TBC in the supplied draft. Confirm rate, terms, Swansea location and halal details before making visible."
    },
    {
      "id": "falafel-stall",
      "name": "The Falafel Stall",
      "kind": "exclusive",
      "category": "Food & drink",
      "status": "draft",
      "discount": "",
      "strapline": "",
      "area": "Swansea",
      "address": "",
      "claimMethod": "",
      "steps": [],
      "terms": [],
      "sourceLabel": "",
      "sourceUrl": "",
      "locationSourceUrl": "",
      "checkedOn": "",
      "expiresOn": "",
      "food": true,
      "halalStatus": "unconfirmed",
      "halalNote": "",
      "halalSourceUrl": "",
      "note": "Listed as Discount TBC in the supplied draft. Confirm rate, terms, Swansea location and halal details before making visible."
    },
    {
      "id": "cha-cha-stall",
      "name": "Cha Cha Stall",
      "kind": "exclusive",
      "category": "Food & drink",
      "status": "draft",
      "discount": "",
      "strapline": "",
      "area": "Swansea",
      "address": "",
      "claimMethod": "",
      "steps": [],
      "terms": [],
      "sourceLabel": "",
      "sourceUrl": "",
      "locationSourceUrl": "",
      "checkedOn": "",
      "expiresOn": "",
      "food": true,
      "halalStatus": "unconfirmed",
      "halalNote": "",
      "halalSourceUrl": "",
      "note": "Listed as Discount TBC in the supplied draft. Confirm rate, terms, Swansea location and halal details before making visible."
    },
    {
      "id": "maswana",
      "name": "Maswana",
      "kind": "unclassified",
      "category": "Food & drink",
      "status": "draft",
      "discount": "10% off",
      "strapline": "",
      "area": "Swansea",
      "address": "",
      "claimMethod": "",
      "steps": [],
      "terms": [
        "Cash payment required according to the supplied draft."
      ],
      "sourceLabel": "",
      "sourceUrl": "",
      "locationSourceUrl": "",
      "checkedOn": "",
      "expiresOn": "",
      "food": true,
      "halalStatus": "unconfirmed",
      "halalNote": "",
      "halalSourceUrl": "",
      "note": "The source does not establish whether this is ISOC exclusive or a general offer. Confirm classification, location, conditions and halal details."
    },
    {
      "id": "continue",
      "name": "Continue?",
      "kind": "general",
      "category": "Activities",
      "status": "draft",
      "discount": "25% off",
      "strapline": "",
      "area": "Swansea",
      "address": "",
      "claimMethod": "",
      "steps": [],
      "terms": [],
      "sourceLabel": "",
      "sourceUrl": "",
      "locationSourceUrl": "",
      "checkedOn": "",
      "expiresOn": "",
      "food": false,
      "halalStatus": "not-applicable",
      "halalNote": "",
      "halalSourceUrl": "",
      "note": "The supplied draft attributes 25% to Student Beans. Venue identity, current deal and suitability under the no-pubs requirement are unverified. Kept unpublished."
    }
  ]
};
